import Wrapper from './components/shared/Wrapper/Index'
import Navbar from './components/views/Navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'

const inter = Montserrat({ 
  subsets: ['latin'],
  weight : ["400", "500","600"],


})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
        <Navbar/>

        {children}
        
        </Wrapper>
        </body>
    </html>
  )
}
